project_id = "gakxasjrvixvauulqenf"

[functions.kaggle-datasets]
verify_jwt = false

[functions.pinata-upload]
verify_jwt = false

[functions.verify-purchase]
verify_jwt = false

[functions.auth-login]
verify_jwt = false

[functions.get-purchases]
verify_jwt = false